import "server-only";
import { PrismaPg } from "@prisma/adapter-pg";
// Generated by `prisma generate` from the `prisma-client` generator
// (engineType = "client", Rust-free/WASM query compiler) into
// src/generated/prisma, per prisma/schema.prisma `generator client { }`.
// This directory is gitignored and must exist before this module is
// imported — `npm install` (postinstall) and `npm run build` both run
// `prisma generate` for exactly this reason (see package.json). If you see
// "Module not found: Can't resolve '@/generated/prisma/client'", the
// generate step didn't run; run `npx prisma generate` manually.
import { PrismaClient } from "@/generated/prisma/client";

declare global {
  var __prisma: PrismaClient | undefined;
}

function createPrismaClient(): PrismaClient {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    throw new Error("DATABASE_URL is not set");
  }
  const adapter = new PrismaPg({ connectionString });
  return new PrismaClient({
    adapter,
    log: process.env.NODE_ENV === "development" ? ["warn", "error"] : ["error"],
  });
}

/**
 * Singleton PrismaClient.
 *
 * In development, Next.js hot-reloads server modules, which would otherwise
 * create a new PrismaClient (and a new pg connection pool) on every save.
 * Stashing the instance on `globalThis` avoids that.
 */
export const prisma: PrismaClient = global.__prisma ?? createPrismaClient();

if (process.env.NODE_ENV !== "production") {
  global.__prisma = prisma;
}
