import "server-only";
import { PrismaPg } from "@prisma/adapter-pg";
// Generated by `prisma generate` from the `prisma-client` generator
// (engineType = "client", Rust-free/WASM query compiler) into
// src/generated/prisma, per prisma/schema.prisma `generator client { }`.
//
// NOTE: this path matches Prisma 7.9.0's documented output layout for the
// `prisma-client` generator at the time this was written. This repository's
// sandbox cannot reach binaries.prisma.sh to actually run `prisma generate`
// (see README "Известные ограничения окружения"), so this import is
// unverified against real generated output — confirm the exact file name
// Prisma emits (`client.ts` vs `index.ts`) after running `prisma generate`
// locally, and adjust this import if it differs.
import { PrismaClient } from "@/generated/prisma/client";

declare global {
  var __prisma: PrismaClient | undefined;
}

function createPrismaClient(): PrismaClient {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    throw new Error("DATABASE_URL is not set");
  }
  const adapter = new PrismaPg({ connectionString });
  return new PrismaClient({
    adapter,
    log: process.env.NODE_ENV === "development" ? ["warn", "error"] : ["error"],
  });
}

/**
 * Singleton PrismaClient.
 *
 * In development, Next.js hot-reloads server modules, which would otherwise
 * create a new PrismaClient (and a new pg connection pool) on every save.
 * Stashing the instance on `globalThis` avoids that.
 */
export const prisma: PrismaClient = global.__prisma ?? createPrismaClient();

if (process.env.NODE_ENV !== "production") {
  global.__prisma = prisma;
}
